AWSTemplateFormatVersion: 2010-09-09
Description: ECR Repository for docker-lambda

Resources:
  RepositoryBase:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::ECR::PublicRepository
    Properties:
      RepositoryName: lambda-base
      RepositoryCatalogData:
        OperatingSystems: [ Linux ]
        Architectures: [ "x86-64", "ARM 64" ]
        RepositoryDescription: shogo82148/docker-lambda
        AboutText: |
          # Base Image for AWS Lambda
          TBD

  RepositoryProvided:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::ECR::PublicRepository
    Properties:
      RepositoryName: lambda-provided
      RepositoryCatalogData:
        OperatingSystems: [ Linux ]
        Architectures: [ "x86-64", "ARM 64" ]
        RepositoryDescription: shogo82148/docker-lambda
        AboutText: |
          # Base Image for AWS Lambda
          TBD

  RepositoryNodejs:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::ECR::PublicRepository
    Properties:
      RepositoryName: lambda-nodejs
      RepositoryCatalogData:
        OperatingSystems: [ Linux ]
        Architectures: [ "x86-64", "ARM 64" ]
        RepositoryDescription: shogo82148/docker-lambda
        AboutText: |
          # Base Image for AWS Lambda
          TBD

  RepositoryPython:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::ECR::PublicRepository
    Properties:
      RepositoryName: lambda-python
      RepositoryCatalogData:
        OperatingSystems: [ Linux ]
        Architectures: [ "x86-64", "ARM 64" ]
        RepositoryDescription: shogo82148/docker-lambda
        AboutText: |
          # Base Image for AWS Lambda
          TBD

  RepositoryRuby:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::ECR::PublicRepository
    Properties:
      RepositoryName: lambda-ruby
      RepositoryCatalogData:
        OperatingSystems: [ Linux ]
        Architectures: [ "x86-64", "ARM 64" ]
        RepositoryDescription: shogo82148/docker-lambda
        AboutText: |
          # Base Image for AWS Lambda
          TBD

  RepositoryJava:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::ECR::PublicRepository
    Properties:
      RepositoryName: lambda-java
      RepositoryCatalogData:
        OperatingSystems: [ Linux ]
        Architectures: [ "x86-64", "ARM 64" ]
        RepositoryDescription: shogo82148/docker-lambda
        AboutText: |
          # Base Image for AWS Lambda
          TBD

  RepositoryDotNetCore:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::ECR::PublicRepository
    Properties:
      RepositoryName: lambda-dotnetcore
      RepositoryCatalogData:
        OperatingSystems: [ Linux ]
        Architectures: [ "x86-64", "ARM 64" ]
        RepositoryDescription: shogo82148/docker-lambda
        AboutText: |
          # Base Image for AWS Lambda
          TBD

  RepositoryDotNet:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::ECR::PublicRepository
    Properties:
      RepositoryName: lambda-dotnet
      RepositoryCatalogData:
        OperatingSystems: [ Linux ]
        Architectures: [ "x86-64", "ARM 64" ]
        RepositoryDescription: shogo82148/docker-lambda
        AboutText: |
          # Base Image for AWS Lambda
          TBD

  RepositoryGo:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::ECR::PublicRepository
    Properties:
      RepositoryName: lambda-go
      RepositoryCatalogData:
        OperatingSystems: [ Linux ]
        Architectures: [ "x86-64", "ARM 64" ]
        RepositoryDescription: shogo82148/docker-lambda
        AboutText: |
          # Base Image for AWS Lambda
          TBD
