AWSTemplateFormatVersion: 2010-09-09
Description: ECR Repository for docker-lambda

Resources:
  RepositoryBase:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::ECR::PublicRepository
    Properties:
      RepositoryName: lambda-base
      RepositoryCatalogData:
        OperatingSystems: [ Linux ]
        Architectures: [ "x86-64", "ARM 64" ]
        RepositoryDescription: shogo82148/docker-lambda
        AboutText: |
          # Base Image for AWS Lambda
          TBD

  RepositoryProvided:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::ECR::PublicRepository
    Properties:
      RepositoryName: lambda-provided
      RepositoryCatalogData:
        OperatingSystems: [ Linux ]
        Architectures: [ "x86-64", "ARM 64" ]
        RepositoryDescription: shogo82148/docker-lambda
        AboutText: |
          # Base Image for AWS Lambda
          TBD

  RepositoryNodejs:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::ECR::PublicRepository
    Properties:
      RepositoryName: lambda-nodejs
      RepositoryCatalogData:
        OperatingSystems: [ Linux ]
        Architectures: [ "x86-64", "ARM 64" ]
        RepositoryDescription: shogo82148/docker-lambda
        AboutText: |
          # Base Image for AWS Lambda
          TBD

  RepositoryPython:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::ECR::PublicRepository
    Properties:
      RepositoryName: lambda-python
      RepositoryCatalogData:
        OperatingSystems: [ Linux ]
        Architectures: [ "x86-64", "ARM 64" ]
        RepositoryDescription: shogo82148/docker-lambda
        AboutText: |
          # Base Image for AWS Lambda
          TBD

  DeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      # trust policy for using https://github.com/fuller-inc/actions-aws-assume-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - 'sts:AssumeRole'
            Condition:
              StringEquals:
                "sts:ExternalId": shogo82148/docker-lambda
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::053160724612:root
            Action:
              - 'sts:TagSession'
      Policies:
        - PolicyName: Deployment
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "ecr-public:*"
                Resource:
                  - !GetAtt RepositoryBase.Arn
                  - !GetAtt RepositoryProvided.Arn
                  - !GetAtt RepositoryNodejs.Arn
                  - !GetAtt RepositoryPython.Arn
              - Effect: Allow
                Action:
                  - "ecr-public:GetAuthorizationToken"
                  - "sts:GetServiceBearerToken"
                Resource: "*"
