name: Build base.al2023 build image

on:
  push:
    branches:
      - main
    tags:
      - "base.al2023-build/*"
  pull_request:
    paths:
      - ".github/workflows/base.al2023-build.yml"
      - "dockerfiles/base.al2023/build/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - name: build
        run: dockerfiles/base.al2023/build-build.sh

      - name: Publish to DockerHub
        env:
          USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          printenv PASSWORD | docker login --username shogo82148 --password-stdin
          dockerfiles/base.al2023/publish-build.sh shogo82148
          docker logout

      - name: Publish to GitHub Packages Container registry
        env:
          USERNAME: ${{ github.repository_owner }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          printenv PASSWORD | docker login --username "$USERNAME" --password-stdin ghcr.io
          dockerfiles/base.al2023/publish-build.sh "ghcr.io/$USERNAME"
          docker logout
