name: Build java8 run image

on:
  push:
    branches:
      - main
    tags:
      - "java8-run/*"
  pull_request:
    paths:
      - ".github/workflows/java8-run.yml"
      - "java8/run/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
