name: maintain

on:
  schedule:
    - cron: "58 6 * * 1"
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    # ref. https://github.com/fuller-inc/actions-aws-assume-role#about-security-hardening-with-openid-connect
    permissions:
      id-token: write
      statuses: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: fuller-inc/actions-aws-assume-role@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::445285296882:role/lambda-docker-repository-DeploymentRole-1HRJZXKHD4SPU
          role-session-tagging: true
      - run: .github/delete-untagged-images.sh lambda-base
      - run: .github/delete-untagged-images.sh lambda-dotnet
      - run: .github/delete-untagged-images.sh lambda-dotnetcore
      - run: .github/delete-untagged-images.sh lambda-go
      - run: .github/delete-untagged-images.sh lambda-java
      - run: .github/delete-untagged-images.sh lambda-nodejs
      - run: .github/delete-untagged-images.sh lambda-provided
      - run: .github/delete-untagged-images.sh lambda-python
      - run: .github/delete-untagged-images.sh lambda-ruby
