name: Build nodejs16.x run image

on:
  push:
    branches:
      - main
    tags:
      - "nodejs16.x-run/*"
  pull_request:
    paths:
      - ".github/workflows/nodejs16.x-run.yml"
      - "dockerfiles/nodejs16.x/run/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - name: build
        run: dockerfiles/nodejs16.x/build-run.sh

      - name: Publish to DockerHub
        env:
          USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          printenv PASSWORD | docker login --username "$USERNAME" --password-stdin
          dockerfiles/nodejs16.x/publish-run.sh "$USERNAME"
          docker logout

      - name: Publish to GitHub Packages Container registry
        env:
          USERNAME: ${{ github.repository_owner }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          printenv PASSWORD | docker login --username "$USERNAME" --password-stdin ghcr.io
          dockerfiles/nodejs16.x/publish-run.sh "ghcr.io/$USERNAME"
          docker logout
