name: Build python3.8 run image

on:
  push:
    tags:
      - "python3.8-run/*"
  pull_request:
    paths:
      - ".github/workflows/python3.8-run.yml"
      - "dockerfiles/python3.8/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: fuller-inc/actions-aws-assume-role@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::445285296882:role/lambda-docker-repository-DeploymentRole-1HRJZXKHD4SPU
          role-session-tagging: true

      # login ECR Public Registry here to avoid the rate limit
      - name: Login to ECR Public Registry
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/shogo82148

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.40"
      - name: build
        run: dockerfiles/python3.8/build-run.sh

      - name: Publish to DockerHub
        env:
          USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          printenv PASSWORD | docker login --username "$USERNAME" --password-stdin
          dockerfiles/python3.8/publish-run.sh "$USERNAME"
          docker logout

      - name: Publish to GitHub Packages Container registry
        env:
          USERNAME: ${{ github.repository_owner }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          printenv PASSWORD | docker login --username "$USERNAME" --password-stdin ghcr.io
          dockerfiles/python3.8/publish-run.sh "ghcr.io/$USERNAME"
          docker logout ghcr.io

      - name: Publish to ECR Public Registry
        run: |
          dockerfiles/python3.8/publish-run.sh "public.ecr.aws/shogo82148"
