name: Build python3.10 run image

on:
  push:
    branches:
      - main
    tags:
      - "python3.10-run/*"
  pull_request:
    paths:
      - ".github/workflows/python3.10-run.yml"
      - "dockerfiles/python3.10/run/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - name: build
        run: dockerfiles/python3.10/build-run.sh

      - name: Publish to DockerHub
        env:
          USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          printenv PASSWORD | docker login --username shogo82148 --password-stdin
          dockerfiles/python3.10/publish-run.sh shogo82148
          docker logout

      - name: Publish to GitHub Packages Container registry
        env:
          USERNAME: ${{ github.repository_owner }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          printenv PASSWORD | docker login --username "$USERNAME" --password-stdin ghcr.io
          dockerfiles/python3.10/publish-run.sh "ghcr.io/$USERNAME"
          docker logout
