name: Build python3.9 build image

on:
  push:
    branches:
      - main
    tags:
      - "python3.9-build/*"
  pull_request:
    paths:
      - ".github/workflows/python3.9-build.yml"
      - "python3.9/build/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
