name: release

on:
  schedule:
    - cron: "28 2 * * *"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    # ref. https://github.com/fuller-inc/actions-aws-assume-role#about-security-hardening-with-openid-connect
    permissions:
      id-token: write
      contents: read

    steps:
      # secrets.GITHUB_TOKEN doesn't start a new workflow run, but we want.
      - id: generate
        uses: shogo82148/actions-github-app-token@v1

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate.outputs.token }}
          fetch-depth: 0 # we need all tags

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.40"

      - run: ./scripts/release.pl --force
