name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: |
          ./test.sh
        working-directory: dump
