name: test

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'dump/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: test
        run: |
          ./test.sh
        working-directory: dump
